# Generated by Django 6.0.5 on 2026-05-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='category',
            field=models.CharField(blank=True, max_length=120, verbose_name='カテゴリ'),
        ),
    ]
