# Generated by Django 6.0.5 on 2026-05-07 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0003_knowledgearticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgearticle',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='tenasapo_knowledge.customer', verbose_name='顧客'),
        ),
    ]
