# Generated by Django 6.0.5 on 2026-05-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0004_alter_knowledgearticle_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=120, verbose_name='大カテゴリ')),
                ('child_name', models.CharField(max_length=120, verbose_name='小カテゴリ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'FAQカテゴリ',
                'verbose_name_plural': 'FAQカテゴリ',
                'ordering': ['parent_name', 'child_name'],
                'constraints': [models.UniqueConstraint(fields=('parent_name', 'child_name'), name='unique_faq_category_pair')],
            },
        ),
    ]
