# Generated by Django 6.0.5 on 2026-05-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0005_faqcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleattachment',
            name='placement',
            field=models.CharField(choices=[('attachment', '添付'), ('question', '質問画像'), ('answer', '回答画像')], default='attachment', max_length=20, verbose_name='表示位置'),
        ),
    ]
