# Generated by Django 6.0.5 on 2026-05-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0007_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='visible_to_customer',
            field=models.BooleanField(default=True, verbose_name='カスタマーユーザー向け表示'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='visible_to_systena',
            field=models.BooleanField(default=True, verbose_name='システナユーザー向け表示'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'カスタマー'), ('systena', 'システナ')], default='customer', max_length=20, verbose_name='ユーザー区分'),
        ),
    ]
