# Generated by Django 6.0.5 on 2026-05-11 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0008_knowledgearticle_visible_to_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='ユーザー名')),
                ('ip_address', models.CharField(blank=True, max_length=64, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('logged_in_at', models.DateTimeField(auto_now_add=True, verbose_name='ログイン日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_histories', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ログイン履歴',
                'verbose_name_plural': 'ログイン履歴',
                'ordering': ['-logged_in_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='ユーザー名')),
                ('page_name', models.CharField(max_length=200, verbose_name='ページ名')),
                ('path', models.CharField(max_length=255, verbose_name='パス')),
                ('ip_address', models.CharField(blank=True, max_length=64, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='閲覧日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_histories', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '閲覧履歴',
                'verbose_name_plural': '閲覧履歴',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
