# Generated by Django 6.0.5 on 2026-05-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0009_loginhistory_viewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewhistory',
            name='category',
            field=models.CharField(blank=True, max_length=120, verbose_name='小カテゴリ'),
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='parent_category',
            field=models.CharField(blank=True, max_length=120, verbose_name='大カテゴリ'),
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='search_query',
            field=models.CharField(blank=True, max_length=200, verbose_name='検索キーワード'),
        ),
    ]
