# Generated by Django 6.0.5 on 2026-05-12 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0010_viewhistory_category_viewhistory_parent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='logged_out_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ログアウト日時'),
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='login_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_histories', to='tenasapo_knowledge.loginhistory', verbose_name='ログイン履歴'),
        ),
    ]
