# Generated by Django 6.0.5 on 2026-05-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0011_loginhistory_logged_out_at_viewhistory_login_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='answer_view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='回答表示回数'),
        ),
    ]
