# Generated by Django 6.0.5 on 2026-05-12 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0012_knowledgearticle_answer_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='tenasapo_knowledge.knowledgearticle', verbose_name='記事')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_goods', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'FAQグッド',
                'verbose_name_plural': 'FAQグッド',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('article', 'user'), name='unique_article_good_per_user')],
            },
        ),
    ]
