# Generated by Django 6.0.5 on 2026-05-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0013_articlegood'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='投稿者名'),
        ),
    ]
