# Generated by Django 6.0.5 on 2026-05-13 05:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0017_knowledgearticle_approved_by_and_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('target_os', models.CharField(blank=True, max_length=120, verbose_name='対象OS')),
                ('category', models.CharField(blank=True, max_length=120, verbose_name='カテゴリ')),
                ('body', models.TextField(verbose_name='内容')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開')),
                ('is_approved', models.BooleanField(default=True, verbose_name='承認済み')),
                ('visible_to_customer', models.BooleanField(default=True, verbose_name='カスタマーユーザー向け表示')),
                ('visible_to_systena', models.BooleanField(default=True, verbose_name='システナユーザー向け表示')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='公開日時')),
                ('created_by_name', models.CharField(blank=True, max_length=150, verbose_name='投稿者名')),
                ('approved_by_name', models.CharField(blank=True, max_length=150, verbose_name='承認者名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tips_articles', to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tips_articles', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'Tips',
                'verbose_name_plural': 'Tips',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
