# Generated by Django 6.0.5 on 2026-05-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0018_tipsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipsarticle',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='tips_attachments/%Y/%m/', verbose_name='PDFファイル'),
        ),
    ]
