# Generated by Django 6.0.5 on 2026-06-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0024_tipsarticle_source_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='reference_links',
            field=models.JSONField(blank=True, default=list, help_text='参照用のURLを保存するリスト', verbose_name='参考リンク'),
        ),
        migrations.AddField(
            model_name='tipsarticle',
            name='reference_links',
            field=models.JSONField(blank=True, default=list, help_text='参照用のURLを保存するリスト', verbose_name='参考リンク'),
        ),
    ]
