# Generated by Django 6.0.5 on 2026-06-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0025_knowledgearticle_reference_links_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ['parent_name', 'middle_name', 'child_name'], 'verbose_name': 'FAQカテゴリ', 'verbose_name_plural': 'FAQカテゴリ'},
        ),
        migrations.RemoveConstraint(
            model_name='faqcategory',
            name='unique_faq_category_pair',
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='中カテゴリ'),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='category',
            field=models.CharField(blank=True, max_length=180, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='tipsarticle',
            name='category',
            field=models.CharField(blank=True, max_length=180, verbose_name='カテゴリ'),
        ),
        migrations.AddConstraint(
            model_name='faqcategory',
            constraint=models.UniqueConstraint(fields=('parent_name', 'middle_name', 'child_name'), name='unique_faq_category_triplet'),
        ),
    ]
