# Generated by Django 6.0.5 on 2026-06-04 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0028_tipsimageattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticleImageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='knowledge_attachments/%Y/%m/', verbose_name='画像ファイル')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='表示名')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tenasapo_knowledge.knowledgearticle', verbose_name='ナレッジ記事')),
            ],
            options={
                'verbose_name': 'ナレッジ記事画像',
                'verbose_name_plural': 'ナレッジ記事画像',
                'ordering': ['uploaded_at', 'id'],
            },
        ),
    ]
