# Generated by Django 6.0.5 on 2026-06-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0029_knowledgearticleimageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='target_os',
            field=models.CharField(blank=True, max_length=120, verbose_name='対象OS'),
        ),
    ]
