# Generated by Django 6.0.5 on 2026-06-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0034_remove_convenience_from_faq_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvenienceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120, verbose_name='カテゴリ')),
                ('target_os', models.CharField(max_length=120, verbose_name='OS')),
                ('shortcut_key', models.CharField(max_length=120, verbose_name='ショートカットキー')),
                ('display_text', models.CharField(max_length=200, verbose_name='表示されるもの')),
                ('image', models.FileField(blank=True, upload_to='manuals/%Y/%m/', verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '便利機能',
                'verbose_name_plural': '便利機能',
                'ordering': ['category', 'display_text', 'id'],
            },
        ),
    ]
