# Generated by Django 6.0.5 on 2026-06-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0035_conveniencefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniencefeature',
            name='usage_frequency',
            field=models.CharField(blank=True, max_length=50, verbose_name='使用頻度'),
        ),
    ]
