# Generated by Django 6.0.5 on 2026-06-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0036_conveniencefeature_usage_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conveniencefeature',
            name='usage_frequency',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=1, verbose_name='使用頻度'),
        ),
    ]
