# Generated by Django 6.0.5 on 2026-06-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0037_alter_conveniencefeature_usage_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniencefeature',
            name='middle_category',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='中カテゴリ'),
        ),
    ]
