# Generated by Django 6.0.5 on 2026-06-09 23:54

from django.db import migrations, models


def migrate_quick_reference_structure(apps, schema_editor):
    ConvenienceFeature = apps.get_model('tenasapo_knowledge', 'ConvenienceFeature')

    for feature in ConvenienceFeature.objects.all():
        old_category = (feature.category or '').strip()
        old_middle = (feature.middle_category or '').strip()

        if old_category == 'ファイル名を指定して実行':
            feature.reference_type = 'command'
        else:
            feature.reference_type = 'shortcut'

        if old_middle:
            feature.category = old_middle
            feature.middle_category = ''

        feature.save(update_fields=['reference_type', 'category', 'middle_category'])


def reverse_quick_reference_structure(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0038_conveniencefeature_middle_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conveniencefeature',
            options={'ordering': ['reference_type', 'category', 'middle_category', 'display_text', 'id'], 'verbose_name': 'クイックリファレンス', 'verbose_name_plural': 'クイックリファレンス'},
        ),
        migrations.AddField(
            model_name='conveniencefeature',
            name='note',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='conveniencefeature',
            name='reference_type',
            field=models.CharField(choices=[('shortcut', 'ショートカット'), ('command', 'コマンド')], default='shortcut', max_length=20, verbose_name='種別'),
        ),
        migrations.RunPython(migrate_quick_reference_structure, reverse_quick_reference_structure),
    ]
