# Generated by Django 6.0.5 on 2026-06-10 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0039_alter_conveniencefeature_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conveniencefeature',
            name='display_text',
            field=models.CharField(max_length=200, verbose_name='内容'),
        ),
        migrations.CreateModel(
            name='ConvenienceFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='tenasapo_knowledge.conveniencefeature', verbose_name='クイックリファレンス')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenience_favorites', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'クイックリファレンスお気に入り',
                'verbose_name_plural': 'クイックリファレンスお気に入り',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('feature', 'user'), name='unique_convenience_favorite_per_user')],
            },
        ),
    ]
