# Generated by Django 6.0.5 on 2026-06-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0040_alter_conveniencefeature_display_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conveniencefeature',
            name='target_os',
        ),
    ]
