# Generated by Django 6.0.5 on 2026-06-17 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0043_tipsarticle_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by_name', models.CharField(max_length=150, verbose_name='更新者')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='更新日')),
                ('category', models.CharField(choices=[('new_feature', '新規機能追加'), ('update', '更新/改修'), ('delete', '削除')], max_length=20, verbose_name='カテゴリ')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='タイトル')),
                ('update_content', models.TextField(blank=True, verbose_name='更新内容')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_histories', to=settings.AUTH_USER_MODEL, verbose_name='更新者ユーザー')),
            ],
            options={
                'verbose_name': '改訂履歴',
                'verbose_name_plural': '改訂履歴',
                'ordering': ['-update_date', '-id'],
            },
        ),
    ]
