# Generated by Django 6.0.5 on 2026-06-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0047_knowledgearticle_standard_contract_only_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revisionhistory',
            options={'ordering': ['-update_date', '-id'], 'verbose_name': '更新履歴', 'verbose_name_plural': '更新履歴'},
        ),
        migrations.AddField(
            model_name='conveniencefeature',
            name='management_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='管理番号'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='management_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='管理番号'),
        ),
        migrations.AddField(
            model_name='tipsarticle',
            name='management_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='管理番号'),
        ),
    ]
