# Generated by Django 6.0.5 on 2026-07-13 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0052_relatedtag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionhistory',
            name='category',
            field=models.CharField(choices=[('new_feature', '新規機能追加'), ('update', '更新/改修'), ('bug_fix', '不具合修正'), ('delete', '削除')], max_length=20, verbose_name='カテゴリ'),
        ),
        migrations.CreateModel(
            name='VerificationReportTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120, verbose_name='カテゴリ')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_report_topics', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '検証報告タイトル',
                'verbose_name_plural': '検証報告タイトル',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VerificationReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=200, verbose_name='サブタイトル')),
                ('summary', models.TextField(blank=True, verbose_name='概要')),
                ('steps', models.TextField(blank=True, verbose_name='手順')),
                ('cautions', models.TextField(blank=True, verbose_name='注意事項')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_report_entries', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tenasapo_knowledge.verificationreporttopic', verbose_name='タイトル')),
            ],
            options={
                'verbose_name': '検証報告詳細',
                'verbose_name_plural': '検証報告詳細',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
