# Generated by Django 6.0.5 on 2026-07-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0052_relatedtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name='所属部署'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.CharField(blank=True, max_length=255, verbose_name='グループ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='役職'),
        ),
        migrations.AlterField(
            model_name='revisionhistory',
            name='category',
            field=models.CharField(choices=[('new_feature', '新規機能追加'), ('update', '更新/改修'), ('bug_fix', '不具合修正'), ('delete', '削除')], max_length=20, verbose_name='カテゴリ'),
        ),
    ]
