# Generated by Django 6.0.5 on 2026-07-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0053_alter_revisionhistory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='auth_account_email',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='認証アカウントメール'),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='auth_account_uid',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='認証アカウントUID'),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='auth_provider',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='認証プロバイダ'),
        ),
    ]
