# Generated by Django 6.0.5 on 2026-07-14 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0054_loginhistory_auth_account_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationreportentry',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='verification_reports/%Y/%m/', verbose_name='PDFファイル'),
        ),
        migrations.CreateModel(
            name='VerificationReportEntryImageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='verification_report_images/%Y/%m/', verbose_name='画像ファイル')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='表示名')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tenasapo_knowledge.verificationreportentry', verbose_name='検証内容')),
            ],
            options={
                'verbose_name': '検証内容画像',
                'verbose_name_plural': '検証内容画像',
                'ordering': ['uploaded_at', 'id'],
            },
        ),
    ]
