# Generated by Django 6.0.5 on 2026-07-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0056_loginhistory_auth_fields_default_empty'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipsAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tips_attachments/%Y/%m/', verbose_name='ファイル')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='表示名')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tenasapo_knowledge.tipsarticle', verbose_name='Tips')),
            ],
            options={
                'verbose_name': 'Tips添付ファイル',
                'verbose_name_plural': 'Tips添付ファイル',
                'ordering': ['uploaded_at', 'id'],
            },
        ),
    ]
