# Generated by Django 6.0.5 on 2026-08-24 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0059_alter_remand_reason_verbose_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=60, verbose_name='案件番号')),
                ('project_name', models.CharField(max_length=200, verbose_name='案件名')),
                ('title', models.CharField(max_length=200, verbose_name='ドキュメントタイトル')),
                ('category', models.CharField(max_length=180, verbose_name='カテゴリ')),
                ('document_type', models.CharField(choices=[('procedure', '手順書'), ('hearing_sheet', 'ヒアリングシート'), ('parameter_sheet', 'パラメータシート')], max_length=30, verbose_name='分類')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='ドキュメント')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開')),
                ('created_by_name', models.CharField(blank=True, max_length=150, verbose_name='アップロード者名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_documents', to=settings.AUTH_USER_MODEL, verbose_name='アップロード者')),
            ],
            options={
                'verbose_name': 'ドキュメント保管',
                'verbose_name_plural': 'ドキュメント保管',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
