# Generated by Django 6.0.5 on 2026-08-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0060_projectdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='projectdocument',
            name='project_name',
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='customer_name',
            field=models.CharField(default='', max_length=200, verbose_name='顧客名'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='file_office',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='Officeドキュメント'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='PDFドキュメント'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='製品名'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='product_version',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='バージョン'),
        ),
    ]
