# Generated by Django 6.0.5 on 2026-08-25 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0061_remove_projectdocument_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocumentRevisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by_name', models.CharField(max_length=150, verbose_name='更新者名')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日時')),
                ('revision_note', models.TextField(verbose_name='更新内容')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='tenasapo_knowledge.projectdocument', verbose_name='対象ドキュメント')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_document_revisions', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'プロジェクトドキュメント更新履歴',
                'verbose_name_plural': 'プロジェクトドキュメント更新履歴',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
