# Generated by Django 6.0.5 on 2026-08-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0062_projectdocumentrevisionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocumentrevisionhistory',
            name='file_office',
            field=models.FileField(blank=True, null=True, upload_to='documents_revisions/%Y/%m/', verbose_name='Officeドキュメント'),
        ),
        migrations.AddField(
            model_name='projectdocumentrevisionhistory',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents_revisions/%Y/%m/', verbose_name='PDFドキュメント'),
        ),
    ]
