# Generated by Django 6.0.5 on 2026-08-26 00:16

import tenasapo_knowledge.models
import tenasapo_knowledge.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0063_projectdocumentrevisionhistory_file_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='file_office',
            field=models.FileField(blank=True, null=True, storage=tenasapo_knowledge.storage.HybridGoogleDriveStorage(), upload_to=tenasapo_knowledge.models.project_document_upload_path, verbose_name='Officeドキュメント'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, storage=tenasapo_knowledge.storage.HybridGoogleDriveStorage(), upload_to=tenasapo_knowledge.models.project_document_upload_path, verbose_name='PDFドキュメント'),
        ),
        migrations.AlterField(
            model_name='projectdocumentrevisionhistory',
            name='file_office',
            field=models.FileField(blank=True, null=True, storage=tenasapo_knowledge.storage.HybridGoogleDriveStorage(), upload_to=tenasapo_knowledge.models.project_document_revision_upload_path, verbose_name='Officeドキュメント'),
        ),
        migrations.AlterField(
            model_name='projectdocumentrevisionhistory',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, storage=tenasapo_knowledge.storage.HybridGoogleDriveStorage(), upload_to=tenasapo_knowledge.models.project_document_revision_upload_path, verbose_name='PDFドキュメント'),
        ),
    ]
