# Generated by Django 6.0.5 on 2026-08-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0064_alter_projectdocument_file_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='テンプレート'),
        ),
    ]
