# Generated by Django 6.0.5 on 2026-08-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0065_projectdocument_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='is_corrected',
            field=models.BooleanField(default=False, verbose_name='修正済み'),
        ),
        migrations.AddField(
            model_name='tipsarticle',
            name='is_corrected',
            field=models.BooleanField(default=False, verbose_name='修正済み'),
        ),
    ]
