# Generated by Django 6.0.5 on 2026-09-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0066_knowledgearticle_is_corrected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exclude_from_analysis',
            field=models.BooleanField(default=True, verbose_name='成果分析から除外する（アナライズ非表示）'),
        ),
    ]
