# Generated by Django 6.0.5 on 2026-09-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0067_userprofile_exclude_from_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='exclude_from_analysis',
            field=models.BooleanField(default=False, verbose_name='成果分析から除外する（アナライズ非表示）'),
        ),
    ]
