# Generated by Django 6.0.5 on 2026-09-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenasapo_knowledge', '0068_alter_userprofile_exclude_from_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='exclude_from_analysis',
            field=models.BooleanField(default=False, verbose_name='アナライズから除外する'),
        ),
    ]
