from django.urls import path
from django.views.generic import RedirectView
from .views import (
    ArticleListView,
    ArticleManagementView,
    ConvenienceCreateView,
    ConvenienceListView,
    ConvenienceFavoriteToggleView,
    ConvenienceUpdateView,
    ArticleAttachmentDeleteView,
    FirstLoginRegistrationView,
    HomeView,
    LoginLandingPageView,
    FAQCategoryCreateView,
    FAQCategoryUpdateView,
    RelatedTagCreateView,
    FAQFavoriteToggleView,
    FAQGoodToggleView,
    FAQAnswerViewTrackView,
    PreviewRenderView,
    KnowledgeArticleCreateView,
    KnowledgeArticleDeleteView,
    KnowledgeArticleApproveView,
    KnowledgeArticleApprovalResetView,
    KnowledgeArticleRemandView,
    KnowledgeArticleImageAttachmentDeleteView,
    KnowledgeArticleDetailView,
    KnowledgeInputHubView,
    KnowledgeArticleUpdateView,
    LoginHistoryListView,
    ManualCreateView,
    ManualDeleteView,
    ManualDetailView,
    ManualListView,
    ManualUpdateView,
    ProjectDocumentCreateView,
    ProjectDocumentListView,
    ProjectDocumentUpdateView,
    ProjectDocumentDeleteView,
    ProjectDocumentRevisionHistoryAPIView,
    MailDraftCallbackView,
    RevisionHistoryCreateView,
    RevisionHistoryDeleteView,
    RevisionHistoryListView,
    RevisionHistoryUpdateView,
    ReviewListView,
    SummaryView,
    SummaryPDFView,
    SummaryNotifyChatAPIView,
    TipsApproveView,
    TipsApprovalResetView,
    TipsRemandView,
    TipsCreateView,
    TipsDeleteView,
    TipsFavoriteToggleView,
    TipsGoodToggleView,
    TipViewTrackView,
    KnowledgeFileDownloadView,
    TipsAttachmentDeleteView,
    TipsImageAttachmentDeleteView,
    TipsArticleDetailView,
    TipsListView,
    TipsUpdateView,
    UserCreateView,
    UserDemoIssueView,
    UserDeleteView,
    UserDetailView,
    ViewHistoryListView,
    UserListView,
    UserPasswordResetView,
    UserUpdateView,
    switch_account_view_mode,
)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('first-login-registration/', FirstLoginRegistrationView.as_view(), name='first_login_registration'),
    path('login-lp/', LoginLandingPageView.as_view(), name='login_lp'),
    path('faq/', ArticleListView.as_view(), name='article_list'),
    path('tips/', TipsListView.as_view(), name='tip_list'),
    path('documents/', ProjectDocumentListView.as_view(), name='project_document_list'),
    path('documents/create/', ProjectDocumentCreateView.as_view(), name='project_document_create'),
    path('documents/<int:pk>/edit/', ProjectDocumentUpdateView.as_view(), name='project_document_edit'),
    path('documents/<int:pk>/delete/', ProjectDocumentDeleteView.as_view(), name='project_document_delete'),
    path('documents/<int:pk>/revisions/', ProjectDocumentRevisionHistoryAPIView.as_view(), name='project_document_revisions'),
    path('convenience/', ConvenienceListView.as_view(), name='convenience_list'),
    path('convenience/create/', ConvenienceCreateView.as_view(), name='convenience_create'),
    path('convenience/<int:pk>/edit/', ConvenienceUpdateView.as_view(), name='convenience_edit'),
    path('convenience/toggle-favorite/', ConvenienceFavoriteToggleView.as_view(), name='convenience_toggle_favorite'),
    path('tips/toggle-good/', TipsGoodToggleView.as_view(), name='tip_toggle_good'),
    path('tips/toggle-favorite/', TipsFavoriteToggleView.as_view(), name='tip_toggle_favorite'),
    path('tips/track-view/', TipViewTrackView.as_view(), name='tip_track_view'),
    path('tips/create/', TipsCreateView.as_view(), name='tip_create'),
    path('tips/<int:pk>/edit/', TipsUpdateView.as_view(), name='tip_edit'),
    path('tips/<int:pk>/approve/', TipsApproveView.as_view(), name='tip_approve'),
    path('tips/<int:pk>/approval-reset/', TipsApprovalResetView.as_view(), name='tip_approval_reset'),
    path('tips/<int:pk>/remand/', TipsRemandView.as_view(), name='tip_remand'),
    path('tips/<int:pk>/delete/', TipsDeleteView.as_view(), name='tip_delete'),
    path('tips/detail/<str:management_code>/', TipsArticleDetailView.as_view(), name='tip_detail'),
    path('tips/images/<int:pk>/delete/', TipsImageAttachmentDeleteView.as_view(), name='tip_image_delete'),
    path('tips/attachments/<int:pk>/delete/', TipsAttachmentDeleteView.as_view(), name='tip_attachment_delete'),
    path('knowledge/images/<int:pk>/delete/', KnowledgeArticleImageAttachmentDeleteView.as_view(), name='article_image_delete'),
    path('files/<str:kind>/<int:pk>/', KnowledgeFileDownloadView.as_view(), name='knowledge_file_download'),
    path('knowledge/track-answer-view/', FAQAnswerViewTrackView.as_view(), name='faq_answer_track_view'),
    path('knowledge/toggle-good/', FAQGoodToggleView.as_view(), name='faq_toggle_good'),
    path('knowledge/toggle-favorite/', FAQFavoriteToggleView.as_view(), name='faq_toggle_favorite'),
    path('knowledge/preview-render/', PreviewRenderView.as_view(), name='preview_render'),
    path('knowledge/create/', KnowledgeArticleCreateView.as_view(), name='article_create'),
    path('knowledge/input/', KnowledgeInputHubView.as_view(), name='knowledge_input'),
    path('knowledge/<int:pk>/edit/', KnowledgeArticleUpdateView.as_view(), name='article_edit'),
    path('knowledge/<int:pk>/approve/', KnowledgeArticleApproveView.as_view(), name='article_approve'),
    path('knowledge/<int:pk>/approval-reset/', KnowledgeArticleApprovalResetView.as_view(), name='article_approval_reset'),
    path('knowledge/<int:pk>/remand/', KnowledgeArticleRemandView.as_view(), name='article_remand'),
    path('knowledge/<int:pk>/delete/', KnowledgeArticleDeleteView.as_view(), name='article_delete'),
    path('knowledge/detail/<str:management_code>/', KnowledgeArticleDetailView.as_view(), name='article_detail'),
    path(
        'attachments/<int:pk>/delete/',
        ArticleAttachmentDeleteView.as_view(),
        name='attachment_delete',
    ),
    path('categories/create/', FAQCategoryCreateView.as_view(), name='category_create'),
    path('categories/<int:pk>/edit/', FAQCategoryUpdateView.as_view(), name='category_edit'),
    path('tags/create/', RelatedTagCreateView.as_view(), name='tag_create'),
    path('users/', UserListView.as_view(), name='user_list'),
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/issue-demo/', UserDemoIssueView.as_view(), name='user_demo_issue'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('users/<int:pk>/edit/', UserUpdateView.as_view(), name='user_edit'),
    path('users/<int:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
    path('histories/logins/', LoginHistoryListView.as_view(), name='login_history_list'),
    path('histories/revisions/create/', RevisionHistoryCreateView.as_view(), name='revision_history_create'),
    path('histories/revisions/<int:pk>/edit/', RevisionHistoryUpdateView.as_view(), name='revision_history_edit'),
    path('histories/revisions/<int:pk>/delete/', RevisionHistoryDeleteView.as_view(), name='revision_history_delete'),
    path('histories/revisions/', RevisionHistoryListView.as_view(), name='revision_history_list'),
    path('histories/views/', ViewHistoryListView.as_view(), name='view_history_list'),
    path('summary/', SummaryView.as_view(), name='summary'),
    path('summary/pdf/', SummaryPDFView.as_view(), name='summary_pdf'),
    path('summary/notify/', SummaryNotifyChatAPIView.as_view(), name='summary_notify_chat'),
    path(
        'users/<int:pk>/reset-password/',
        UserPasswordResetView.as_view(),
        name='user_password_reset',
    ),
    # マニュアル
    path('manuals', RedirectView.as_view(pattern_name='manual_list', permanent=False)),
    path('manuals/', ManualListView.as_view(), name='manual_list'),
    path('manuals/<int:pk>/', ManualDetailView.as_view(), name='manual_detail'),
    path('manuals/create/', ManualCreateView.as_view(), name='manual_create'),
    path('manuals/<int:pk>/edit/', ManualUpdateView.as_view(), name='manual_edit'),
    path('manuals/<int:pk>/delete/', ManualDeleteView.as_view(), name='manual_delete'),
    path('management/articles/', ArticleManagementView.as_view(), name='article_management'),
    path('management/reviews/', ReviewListView.as_view(), name='review_list'),
    path('management/mail-draft-callback/', MailDraftCallbackView.as_view(), name='mail_draft_callback'),
    path('account/view-mode/', switch_account_view_mode, name='switch_account_view_mode'),
]
