from django.urls import path
from django.views.generic import RedirectView
from .views import (
    ArticleListView,
    ConvenienceCreateView,
    ConvenienceListView,
    ConvenienceFavoriteToggleView,
    ConvenienceUpdateView,
    ArticleAttachmentDeleteView,
    HomeView,
    FAQCategoryCreateView,
    FAQCategoryUpdateView,
    FAQFavoriteToggleView,
    FAQGoodToggleView,
    FAQAnswerViewTrackView,
    PreviewRenderView,
    KnowledgeArticleCreateView,
    KnowledgeArticleDeleteView,
    KnowledgeArticleApproveView,
    KnowledgeArticleImageAttachmentDeleteView,
    KnowledgeArticleUpdateView,
    LoginHistoryListView,
    ManualCreateView,
    ManualDeleteView,
    ManualDetailView,
    ManualListView,
    ManualUpdateView,
    SummaryView,
    TipsApproveView,
    TipsCreateView,
    TipsDeleteView,
    TipsFavoriteToggleView,
    TipsGoodToggleView,
    TipsImageAttachmentDeleteView,
    TipsListView,
    TipsUpdateView,
    UserCreateView,
    UserDeleteView,
    ViewHistoryListView,
    UserListView,
    UserPasswordResetView,
    UserUpdateView,
)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('faq/', ArticleListView.as_view(), name='article_list'),
    path('tips/', TipsListView.as_view(), name='tip_list'),
    path('convenience/', ConvenienceListView.as_view(), name='convenience_list'),
    path('convenience/create/', ConvenienceCreateView.as_view(), name='convenience_create'),
    path('convenience/<int:pk>/edit/', ConvenienceUpdateView.as_view(), name='convenience_edit'),
    path('convenience/toggle-favorite/', ConvenienceFavoriteToggleView.as_view(), name='convenience_toggle_favorite'),
    path('tips/toggle-good/', TipsGoodToggleView.as_view(), name='tip_toggle_good'),
    path('tips/toggle-favorite/', TipsFavoriteToggleView.as_view(), name='tip_toggle_favorite'),
    path('tips/create/', TipsCreateView.as_view(), name='tip_create'),
    path('tips/<int:pk>/edit/', TipsUpdateView.as_view(), name='tip_edit'),
    path('tips/<int:pk>/approve/', TipsApproveView.as_view(), name='tip_approve'),
    path('tips/<int:pk>/delete/', TipsDeleteView.as_view(), name='tip_delete'),
    path('tips/images/<int:pk>/delete/', TipsImageAttachmentDeleteView.as_view(), name='tip_image_delete'),
    path('knowledge/images/<int:pk>/delete/', KnowledgeArticleImageAttachmentDeleteView.as_view(), name='article_image_delete'),
    path('knowledge/track-answer-view/', FAQAnswerViewTrackView.as_view(), name='faq_answer_track_view'),
    path('knowledge/toggle-good/', FAQGoodToggleView.as_view(), name='faq_toggle_good'),
    path('knowledge/toggle-favorite/', FAQFavoriteToggleView.as_view(), name='faq_toggle_favorite'),
    path('knowledge/preview-render/', PreviewRenderView.as_view(), name='preview_render'),
    path('knowledge/create/', KnowledgeArticleCreateView.as_view(), name='article_create'),
    path('knowledge/<int:pk>/edit/', KnowledgeArticleUpdateView.as_view(), name='article_edit'),
    path('knowledge/<int:pk>/approve/', KnowledgeArticleApproveView.as_view(), name='article_approve'),
    path('knowledge/<int:pk>/delete/', KnowledgeArticleDeleteView.as_view(), name='article_delete'),
    path(
        'attachments/<int:pk>/delete/',
        ArticleAttachmentDeleteView.as_view(),
        name='attachment_delete',
    ),
    path('categories/create/', FAQCategoryCreateView.as_view(), name='category_create'),
    path('categories/<int:pk>/edit/', FAQCategoryUpdateView.as_view(), name='category_edit'),
    path('users/', UserListView.as_view(), name='user_list'),
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/<int:pk>/edit/', UserUpdateView.as_view(), name='user_edit'),
    path('users/<int:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
    path('histories/logins/', LoginHistoryListView.as_view(), name='login_history_list'),
    path('histories/views/', ViewHistoryListView.as_view(), name='view_history_list'),
    path('summary/', SummaryView.as_view(), name='summary'),
    path(
        'users/<int:pk>/reset-password/',
        UserPasswordResetView.as_view(),
        name='user_password_reset',
    ),
    # マニュアル
    path('manuals', RedirectView.as_view(pattern_name='manual_list', permanent=False)),
    path('manuals/', ManualListView.as_view(), name='manual_list'),
    path('manuals/<int:pk>/', ManualDetailView.as_view(), name='manual_detail'),
    path('manuals/create/', ManualCreateView.as_view(), name='manual_create'),
    path('manuals/<int:pk>/edit/', ManualUpdateView.as_view(), name='manual_edit'),
    path('manuals/<int:pk>/delete/', ManualDeleteView.as_view(), name='manual_delete'),
]
