"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-40ny)ii8e%gmt3^jqfrc+ped8gnhymbl6mua@vn2eg7%ow1kqa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '172.16.21.22', 'testserver']
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://172.16.21.22:8000',
    'http://172.16.21.22',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tenasapo_knowledge',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'tenasapo_knowledge.middleware.SafeSessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/


LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'logo',
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

SESSION_COOKIE_AGE = 60 * 30
SESSION_SAVE_EVERY_REQUEST = True

# 業務上のユーザー役割
USER_ROLES = [
    '管理者',
    'レビュアー',
    'システナ',
    'カスタマー',
]

# 後方互換（既存コード/運用向け）
USER_GROUPS = USER_ROLES

USER_GROUP_REVIEWER_NAME = 'レビュアー'

FAQ_APPROVAL_ENABLED = True

# 役割ごとの権限
# 形式: "<app_label>.<codename>"
GROUP_ROLE_PERMISSIONS = {
    '管理者': [
        'tenasapo_knowledge.add_knowledgearticle',
        'tenasapo_knowledge.change_knowledgearticle',
        'tenasapo_knowledge.delete_knowledgearticle',
        'tenasapo_knowledge.view_knowledgearticle',
        'tenasapo_knowledge.add_tipsarticle',
        'tenasapo_knowledge.change_tipsarticle',
        'tenasapo_knowledge.delete_tipsarticle',
        'tenasapo_knowledge.view_tipsarticle',
        'tenasapo_knowledge.add_manual',
        'tenasapo_knowledge.change_manual',
        'tenasapo_knowledge.delete_manual',
        'tenasapo_knowledge.view_manual',
    ],
    'レビュアー': [
        'tenasapo_knowledge.view_knowledgearticle',
        'tenasapo_knowledge.change_knowledgearticle',
        'tenasapo_knowledge.view_tipsarticle',
        'tenasapo_knowledge.change_tipsarticle',
    ],
    'システナ': [
        'tenasapo_knowledge.view_knowledgearticle',
        'tenasapo_knowledge.add_knowledgearticle',
        'tenasapo_knowledge.change_knowledgearticle',
        'tenasapo_knowledge.view_tipsarticle',
        'tenasapo_knowledge.add_tipsarticle',
        'tenasapo_knowledge.change_tipsarticle',
        'tenasapo_knowledge.view_manual',
    ],
    'カスタマー': [
        'tenasapo_knowledge.view_knowledgearticle',
        'tenasapo_knowledge.view_tipsarticle',
    ],
}

# メール設定
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # または使用するSMTPサーバー
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'Tenasapo@gmail.com'  # 送信元メールアドレス
EMAIL_HOST_PASSWORD = 'your-app-password'  # Gmailはアプリパスワード推奨
DEFAULT_FROM_EMAIL = 'your-email@gmail.com'

# メール設定（開発環境：ファイル出力）
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'sent_emails')
DEFAULT_FROM_EMAIL = 'tenasapo@systena.co.jp'
