"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# .env ファイルを読み込む
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-40ny)ii8e%gmt3^jqfrc+ped8gnhymbl6mua@vn2eg7%ow1kqa')
SECRET_KEY = os.getenv('SECRET_KEY', 'f#zjx28!23@8esjhokxzg=x(q@@%d90_x*91x%))voa%@7ud3#')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,172.16.21.22,testserver').split(',')
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000,http://127.0.0.1:8000').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tenasapo_knowledge',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'tenasapo_knowledge.middleware.SafeSessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'tenasapo_knowledge.middleware.LoginRequiredExceptAssetsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tenasapo_knowledge.context_processors.user_display_name',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# 本番環境では PostgreSQL のみ許可（SQLite へのフォールバックを禁止）
is_running_on_azure = bool(os.getenv('WEBSITE_SITE_NAME') or os.getenv('WEBSITE_INSTANCE_ID'))
db_engine = os.getenv('DB_ENGINE', '').strip()

if not db_engine:
    if DEBUG and not is_running_on_azure:
        db_engine = 'django.db.backends.sqlite3'
    else:
        raise ImproperlyConfigured(
            'DB_ENGINE が未設定です。本番環境では django.db.backends.postgresql を設定してください。'
        )

if is_running_on_azure and db_engine != 'django.db.backends.postgresql':
    raise ImproperlyConfigured(
        'Azure App Service では PostgreSQL のみ許可されています。DB_ENGINE=django.db.backends.postgresql を設定してください。'
    )

if db_engine == 'django.db.backends.postgresql':
    required_env_vars = ('DB_NAME', 'DB_USER', 'DB_PASSWORD', 'DB_HOST', 'DB_PORT')
    missing_env_vars = [env_name for env_name in required_env_vars if not os.getenv(env_name)]
    if missing_env_vars:
        missing_text = ', '.join(missing_env_vars)
        raise ImproperlyConfigured(
            f'PostgreSQL 接続情報が不足しています: {missing_text}'
        )

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
            'CONN_MAX_AGE': 600,
            'OPTIONS': {
                'sslmode': 'require',
            }
        }
    }
elif db_engine == 'django.db.backends.sqlite3' and DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    raise ImproperlyConfigured(
        '許可されていない DB_ENGINE です。本番環境では django.db.backends.postgresql を使用してください。'
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/


LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'logo',
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

SESSION_COOKIE_AGE = 60 * 30
SESSION_SAVE_EVERY_REQUEST = True

# 業務上のユーザー役割
# 注: 管理者は権限フィールドで管理、システナ/カスタマーはユーザー区分で管理
USER_ROLES = [
    '投稿者',
    '承認者',
    'demo',
]

# 後方互換（既存コード/運用向け）
USER_GROUPS = USER_ROLES

USER_GROUP_REVIEWER_NAME = '承認者'

FAQ_APPROVAL_ENABLED = True

# 役割ごとの権限
# 形式: "<app_label>.<codename>"
GROUP_ROLE_PERMISSIONS = {
    '管理者': [
        'tenasapo_knowledge.add_knowledgearticle',
        'tenasapo_knowledge.change_knowledgearticle',
        'tenasapo_knowledge.delete_knowledgearticle',
        'tenasapo_knowledge.view_knowledgearticle',
        'tenasapo_knowledge.add_tipsarticle',
        'tenasapo_knowledge.change_tipsarticle',
        'tenasapo_knowledge.delete_tipsarticle',
        'tenasapo_knowledge.view_tipsarticle',
        'tenasapo_knowledge.add_manual',
        'tenasapo_knowledge.change_manual',
        'tenasapo_knowledge.delete_manual',
        'tenasapo_knowledge.view_manual',
    ],
    '承認者': [
        'tenasapo_knowledge.view_knowledgearticle',
        'tenasapo_knowledge.change_knowledgearticle',
        'tenasapo_knowledge.view_tipsarticle',
        'tenasapo_knowledge.change_tipsarticle',
    ],
    'システナ': [
        'tenasapo_knowledge.view_knowledgearticle',
        'tenasapo_knowledge.add_knowledgearticle',
        'tenasapo_knowledge.change_knowledgearticle',
        'tenasapo_knowledge.view_tipsarticle',
        'tenasapo_knowledge.add_tipsarticle',
        'tenasapo_knowledge.change_tipsarticle',
        'tenasapo_knowledge.view_manual',
    ],
    'カスタマー': [
        'tenasapo_knowledge.view_knowledgearticle',
        'tenasapo_knowledge.view_tipsarticle',
    ],
}

# メール設定
# EMAIL_BACKEND を環境変数で切り替え可能にし、未設定時は開発環境ではファイル出力、
# 本番環境では SMTP を使う。
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.filebased.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'Tenasapo@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'your-app-password')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'tenasapo@systena.co.jp')
EMAIL_FILE_PATH = os.getenv('EMAIL_FILE_PATH', os.path.join(BASE_DIR, 'sent_emails'))
